{% set name = "pythermo" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pythermo-{{ version }}.tar.gz
  sha256: 2fd72f4406472d3188a274e9df870e02543868825f12f04a970a42e9e0f0efb4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - matplotlib-base

test:
  imports:
    - pythermo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pythermo/
  summary: Tools for performing computational tasks in the field of low-temperature thermochronology.
  dev_url: https://github.com/OpenThermochronology/PyThermo
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wrguenthner
