{% set name = "pythermo" %}
{% set version = "0.3.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pythermo-{{ version }}.tar.gz
  sha256: 2657684fddf8e6e5afd5e570abd2d87d7de6a18b92ebf380e94772a6b42e7984

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python {{ python_min }}
    - numpy
    - numba
    - scipy
    - matplotlib
    - pandas

test:
  imports:
    - pythermo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pythermo/
  summary: Tools for performing computational tasks in the field of low-temperature thermochronology.
  dev_url: https://github.com/OpenThermochronology/PyThermo
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wrguenthner
